### ISSUE TITLE
Class Not found

### ISSUE THREAD

**Issue by kempyk** [cdeptula/tdeoutputplugin#10]
Hello i have followed the steps carefully and do not experience any of the problems mentioned.  I do however get the following.  Is this a new bug or user error?  It is experienced as soon as i drag the TDE output onto the canvas:

org.pentaho.di.core.exception.KettlePluginException: 
Class not found
org.openbi.kettle.plugins.tableauDataExtract.TDEOutputMeta

	at org.pentaho.di.core.plugins.PluginRegistry.loadClass(PluginRegistry.java:499)
	at org.pentaho.di.core.plugins.PluginRegistry.loadClass(PluginRegistry.java:367)
	at org.pentaho.di.ui.spoon.Spoon.newStep(Spoon.java:6562)
	at org.pentaho.di.ui.spoon.trans.TransGraph$5.drop(TransGraph.java:630)
	at org.eclipse.swt.dnd.DNDListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Unknown Source)
	at org.eclipse.swt.dnd.DropTarget.Drop(Unknown Source)
	at org.eclipse.swt.dnd.DropTarget.Drop_64(Unknown Source)
	at org.eclipse.swt.dnd.DropTarget$3.method6(Unknown Source)
	at org.eclipse.swt.internal.ole.win32.COMObject.callback6(Unknown Source)
	at org.eclipse.swt.internal.ole.win32.COM.DoDragDrop(Native Method)
	at org.eclipse.swt.dnd.DragSource.drag(Unknown Source)
	at org.eclipse.swt.dnd.DragSource.access$000(Unknown Source)
	at org.eclipse.swt.dnd.DragSource$1.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.pentaho.di.ui.spoon.Spoon.readAndDispatch(Spoon.java:1339)
	at org.pentaho.di.ui.spoon.Spoon.waitForDispose(Spoon.java:7939)
	at org.pentaho.di.ui.spoon.Spoon.start(Spoon.java:9214)
	at org.pentaho.di.ui.spoon.Spoon.main(Spoon.java:653)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.pentaho.commons.launcher.Launcher.main(Launcher.java:92)
Caused by: java.lang.ClassNotFoundException: org.openbi.kettle.plugins.tableauDataExtract.TDEOutputMeta
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.pentaho.di.core.plugins.KettleURLClassLoader.loadClassFromParent(KettleURLClassLoader.java:89)
	at org.pentaho.di.core.plugins.KettleURLClassLoader.loadClass(KettleURLClassLoader.java:108)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.pentaho.di.core.plugins.PluginRegistry.loadClass(PluginRegistry.java:494)
	... 30 more

**Comment by cdeptula** [comment]
This error message indicates you are missing the plugin jar TDEOutputPlugin.jar in your plugins/steps/TDEOutputPlugin folder.  I recommend you try uninstalling and re-installing this plugin.
