### ISSUE TITLE
Fails in Pentaho 8.1

### ISSUE THREAD

**Issue by z00mantwo** [cdeptula/tdeoutputplugin#15]
Plugin fails in Pentaho 8.1 with:

org.pentaho.di.core.exception.KettlePluginException: 
Unexpected error loading class with name: org.openbi.kettle.plugins.tableauDataExtract.TDEOutputDialog

Unable to find class loader for plugin: TDEOutputPlugin/Tableau Data Extract Output{class org.pentaho.di.core.plugins.StepPluginType}

	at org.pentaho.di.core.plugins.PluginRegistry.getClass(PluginRegistry.java:846)
	at org.pentaho.di.ui.spoon.delegates.SpoonStepsDelegate.getStepDialog(SpoonStepsDelegate.java:258)
	at org.pentaho.di.ui.spoon.Spoon.getStepEntryDialog(Spoon.java:8822)
	at org.pentaho.di.ui.spoon.delegates.SpoonStepsDelegate.editStep(SpoonStepsDelegate.java:116)
	at org.pentaho.di.ui.spoon.Spoon.editStep(Spoon.java:9006)
	at org.pentaho.di.ui.spoon.trans.TransGraph.editStep(TransGraph.java:3291)
	at org.pentaho.di.ui.spoon.trans.TransGraph.mouseDoubleClick(TransGraph.java:785)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.pentaho.di.ui.spoon.Spoon.readAndDispatch(Spoon.java:1376)
	at org.pentaho.di.ui.spoon.Spoon.waitForDispose(Spoon.java:8161)
	at org.pentaho.di.ui.spoon.Spoon.start(Spoon.java:9523)
	at org.pentaho.di.ui.spoon.Spoon.main(Spoon.java:702)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.pentaho.commons.launcher.Launcher.main(Launcher.java:92)
Caused by: org.pentaho.di.core.exception.KettlePluginException: 
Unable to find class loader for plugin: TDEOutputPlugin/Tableau Data Extract Output{class org.pentaho.di.core.plugins.StepPluginType}

	at org.pentaho.di.core.plugins.PluginRegistry.getClass(PluginRegistry.java:840)
	... 21 more

Note that I had this working correctly in Pentaho 8.0.

**Comment by z00mantwo** [comment]
Here's a patch that will allow this to run in Pentaho 8.1 and an updated icon file. 

[tdeoutputplugin.zip](https://github.com/cdeptula/tdeoutputplugin/files/2431129/tdeoutputplugin.zip)
![tde](https://user-images.githubusercontent.com/43678965/46251867-36fe2d80-c42d-11e8-8234-cc1ec8aae12e.png)

**Comment by z00mantwo** [comment]
I believe this my patch should work with Pentaho PDI 7.0 and up, but I only have access to 8.0 and 8.1. If someone could test with 7.X I would love to know the results.

**Comment by z00mantwo** [comment]
Here's an updated icon that follows the Pentaho 8.1 PDI icon guide at

https://help.pentaho.com/Documentation/8.1/Developer_Center/PDI/Extend/035

![tde](https://user-images.githubusercontent.com/43678965/46359771-f0305380-c637-11e8-950c-ee07e7fe8819.png)

**Comment by cdeptula** [comment]
I fixed this in version 2.0.1 which should be available under the marketplace in the next week.  It can also be downloaded directly from Github.  I was not able to use your icon, but did update it.
