### ISSUE TITLE
Linux PATH problem

### ISSUE THREAD

**Issue by ErikTromp** [cdeptula/tdeoutputplugin#7]
When using the connector in linux (ubuntu) and having the LD_LIBRARY_PATH and PATH set correctly, files put in place, you still get an error about the .so files not being found.

```
2015/01/12 13:53:16 - Tableau Data Extract Output.0 - ERROR (version 5.2.0.0, build 1 from 2014-09-30_19-48-28 by buildguy) : Error initializing step [Tableau Data Extract Output]
2015/01/12 13:53:16 - Tableau Data Extract Output.0 - ERROR (version 5.2.0.0, build 1 from 2014-09-30_19-48-28 by buildguy) : java.lang.UnsatisfiedLinkError: Unable to load library 'DataExtract': libDataExtract.so: cannot open shared object file: No such file or directory
2015/01/12 13:53:16 - Tableau Data Extract Output.0 - 	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:194)
2015/01/12 13:53:16 - Tableau Data Extract Output.0 - 	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:283)
2015/01/12 13:53:16 - Tableau Data Extract Output.0 - 	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:244)
2015/01/12 13:53:16 - Tableau Data Extract Output.0 - 	at com.sun.jna.Native.register(Native.java:1065)
2015/01/12 13:53:16 - Tableau Data Extract Output.0 - 	at com.tableausoftware.DataExtract.TableDefinition.<clinit>(Unknown Source)
2015/01/12 13:53:16 - Tableau Data Extract Output.0 - 	at org.openbi.kettle.plugins.tableauDataExtract.TDEOutput.configureTableDef(Unknown Source)
2015/01/12 13:53:16 - Tableau Data Extract Output.0 - 	at org.openbi.kettle.plugins.tableauDataExtract.TDEOutput.init(Unknown Source)
2015/01/12 13:53:16 - Tableau Data Extract Output.0 - 	at org.pentaho.di.trans.step.StepInitThread.run(StepInitThread.java:69)
2015/01/12 13:53:16 - Tableau Data Extract Output.0 - 	at java.lang.Thread.run(Unknown Source)
2015/01/12 13:53:16 - loading data from XML - ERROR (version 5.2.0.0, build 1 from 2014-09-30_19-48-28 by buildguy) : Step [Tableau Data Extract Output.0] failed to initialize!
2015/01/12 13:53:16 - Tableau Data Extract Output.0 - ERROR (version 5.2.0.0, build 1 from 2014-09-30_19-48-28 by buildguy) : Exception trying to close file: java.lang.NullPointerException
2015/01/12 13:53:16 - Spoon - ERROR (version 5.2.0.0, build 1 from 2014-09-30_19-48-28 by buildguy) : loading data from XML: preparing transformation execution failed
2015/01/12 13:53:16 - Spoon - ERROR (version 5.2.0.0, build 1 from 2014-09-30_19-48-28 by buildguy) : org.pentaho.di.core.exception.KettleException: 
2015/01/12 13:53:16 - Spoon - We failed to initialize at least one step.  Execution can not begin!
2015/01/12 13:53:16 - Spoon - 
2015/01/12 13:53:16 - Spoon - 
2015/01/12 13:53:16 - Spoon - 	at org.pentaho.di.trans.Trans.prepareExecution(Trans.java:1149)
2015/01/12 13:53:16 - Spoon - 	at org.pentaho.di.ui.spoon.trans.TransGraph$27.run(TransGraph.java:3989)
2015/01/12 13:53:16 - Spoon - 	at java.lang.Thread.run(Unknown Source)
2015/01/12 13:53:16 - loading data from XML - ERROR (version 5.2.0.0, build 1 from 2014-09-30_19-48-28 by buildguy) : Errors detected!
2015/01/12 13:53:17 - loading data from XML - ERROR (version 5.2.0.0, build 1 from 2014-09-30_19-48-28 by buildguy) : Errors detected!
```

**Comment by cdeptula** [comment]
This error indicates that your LD_LIBRARY_PATH is not set correctly.  The LD_LIBRARY_PATH variable should point to a directory that contains the libDataExtract.so file.

I just tested this with the latest build and could not replicate the problem when LD_LIBRARY_PATH is set correctly.
